name: Build Android APK

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Find and Build APK
      run: |
        GRADLEW_PATH=$(find . -name "gradlew" -type f | head -n 1)
        if [ -z "$GRADLEW_PATH" ]; then
          echo "Không tìm thấy file gradlew trong dự án!"
          exit 1
        fi
        PROJECT_DIR=$(dirname "$GRADLEW_PATH")
        cd "$PROJECT_DIR"
        chmod +x gradlew
        ./gradlew assembleDebug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-debug
        path: "**/build/outputs/apk/debug/*.apk"
